# Generated by Django 5.0.3 on 2024-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=200)),
                ('price', models.TextField(max_length=200)),
                ('gbjoy', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('simcard', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
